# Generated by Django 5.0.3 on 2024-03-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0002_alter_individual_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
                ('organization_name', models.CharField(blank=True, max_length=250, null=True)),
                ('no_of_persons', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tshirt_size',
            name='chest_inch',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tshirt_size',
            name='length_inch',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('', 'Choose Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('phone_no', models.CharField(max_length=10)),
                ('area', models.TextField()),
                ('tshirt_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freedomrun.tshirt_size')),
            ],
        ),
    ]
