# Generated by Django 5.0.3 on 2024-03-25 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0003_team_family_tshirt_size_chest_inch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freedomrun.team_family'),
        ),
    ]
