# Generated by Django 5.0.4 on 2024-04-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0004_member_team_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='registered_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='registered_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='team_family',
            name='registered_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
