# Generated by Django 5.0.4 on 2024-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0006_team_family_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_family',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
