# Generated by Django 5.0.4 on 2024-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0007_alter_team_family_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_paid',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='individual',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
