# Generated by Django 5.0.4 on 2024-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0009_team_family_is_paid_team_family_paid_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='paid_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team_family',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team_family',
            name='paid_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
