# Generated by Django 5.0.4 on 2024-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0010_coupen_individual_paid_amount_individual_paid_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='individual',
            name='location',
            field=models.CharField(choices=[('', 'Choose location'), ('Coimbatore', 'Coimbatore'), ('Chennai', 'Chennai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(choices=[('', 'Choose location'), ('Coimbatore', 'Coimbatore'), ('Chennai', 'Chennai')], max_length=50),
        ),
    ]
