# Generated by Django 5.0.4 on 2024-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0012_category_delete_location_remove_individual_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team_family',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
