# Generated by Django 5.0.4 on 2025-01-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freedomrun", "0015_alter_individual_category_alter_team_family_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="additional_ph_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                default="O+",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="additional_ph_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                default="O+",
                max_length=10,
                null=True,
            ),
        ),
    ]
