# Generated by Django 5.0.4 on 2025-06-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0016_individual_additional_ph_no_individual_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='category',
            field=models.CharField(choices=[('', 'Choose category '), ('5 KM Walk', '5 KM Walk'), ('5 KM Run', '5 KM Run'), ('10 KM Run', '10 KM Run')], default='5 KM Walk', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team_family',
            name='category',
            field=models.CharField(choices=[('', 'Choose category '), ('5 KM Walk', '5 KM Walk'), ('5 KM Run', '5 KM Run'), ('10 KM Run', '10 KM Run')], default='5 KM Walk', max_length=20, null=True),
        ),
    ]
