# Generated by Django 5.0.4 on 2025-06-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomrun', '0017_alter_individual_category_alter_team_family_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='category',
            field=models.CharField(choices=[('', 'Choose category '), ('10 KM Run', '10 KM Run'), ('5 KM Run', '5 KM Run'), ('5 KM Walk', '5 KM Walk')], default='5 KM Walk', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team_family',
            name='category',
            field=models.CharField(choices=[('', 'Choose category '), ('10 KM Run', '10 KM Run'), ('5 KM Run', '5 KM Run'), ('5 KM Walk', '5 KM Walk')], default='5 KM Walk', max_length=20, null=True),
        ),
    ]
